### ISSUE TITLE
New view with preserved positions of draggable components

### ISSUE THREAD

**Issue by mipmip** [svg-stencils/svg-stencils.github.io#7]
In order to improve usability and give more context to elements, a new presentation in which the original positions are preserved.

This can only be implemented together with the inkscape plugin.

Creative Tim Material Kit could be a nice starter.

- [x] inkscape extension
- [x] svg-stencils nice interface
- [x] fixed canvas width
- [x] zoom functions
- [ ] test with more stencils
- [x] fix ratio problem
